version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aurelia_db
      POSTGRES_USER: aurelia_user
      POSTGRES_PASSWORD: aurelia_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_HOST=postgres
      - CHROMADB_HOST=chromadb
    depends_on:
      - postgres
      - chromadb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api

volumes:
  postgres_data:
  chroma_data: