apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aurelia-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/aurelia-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-key
              key: api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pinecone-key
              key: api-key
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aurelia-frontend
spec:
  template:
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/aurelia-frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_BASE_URL
          value: "https://aurelia-api-xxxxx.run.app"